# Quarkus configuration
quarkus.application.name=SampleComponent
quarkus.http.port=8080

# Locations for externalized configuration
quarkus.config.locations=\
  config/environment.properties,\
  config/credentials.properties,\
  config/esb.properties

# Camel configuration
camel.quarkus.main.name = MyTimerCamel

# Observability — tout le monitoring sur le port 9090
quarkus.management.enabled=true
quarkus.management.port=9090
quarkus.health.enabled=true

# JMX
camel.quarkus.management.enabled=true

#quarkus.log.category."org.apache.activemq.transport.failover".level=WARN